# File: .github/workflows/workflow.yml

on: [push, workflow_dispatch]

name: AzureLoginWithNoSubscriptions

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/checkout@main
    - uses: azure/login@v1
    - uses: azure/deploy@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
